name: save page now

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  spn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Save page now
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: nix run .#spn -- config.yml
